language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - phpunit
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php,ctp,js,css --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=*.min.css,*.min.js --coverage-clover=coverage.xml ./config ./src ./tests; fi
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false